sudo: required

language: minimal

services:
  - docker

install:
  - docker build -t panazzo/s3-side-sync .

script:
  - bash ci/docker_push
#deploy:
#  provider: script
#  script: bash ci/docker_push
#  on:
#    branch: master
