sudo: required

language: minimal

services:
  - docker

install:
  - make build -C ci/ 

script:
    - make push -C ci/
#deploy:
#  provider: script
#  script: bash ci/docker_push
#  on:
#    branch: master
